### ISSUE TITLE
REMOVE ME FROM CONTRIBUTERS PAGE

### ISSUE THREAD

**Issue by Genius398** [FlagClicked/Contributors#18]
REMOVE ME FROM CONTRIBUTERS PAGE
REMOVE ME FROM CONTRIBUTERS PAGE
REMOVE ME FROM CONTRIBUTERS PAGE

**Comment by Genius398** [comment]
@TheColaber  
@TheColaber @Genius398 @TheColaber @TheColaber @TheColaber  REMOVE ME

**Comment by TheColaber** [comment]
I have to ask my lawyer if I could get sued for this.

**Comment by Genius398** [comment]
JUST REMOVE ME

**Comment by Genius398** [comment]
JUST REMOVE ME!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by N3RDIUM** [comment]
@Genius398 You can fork this repo (again) and then remove your name from readme.md and open a pull request, which @TheColaber will (hopefully) merge. 
(If @TheColaber has not visited his lawyer yet)

**Comment by Genius398** [comment]
Thanks dude

**Comment by Genius398** [comment]
#20 #20 #20 #20 #20 #20 #20 #20 #20 #20
